---
- block:
 
  - name: homebrew update/upgrade
    homebrew:
      update_homebrew: true
      upgrade_all: yes
 
  - name: homebrew install
    homebrew:
      name: "{{ item.name }}"
    with_items: "{{ hmbpkg }}"
 
  tags:
    - homebrew
