- block:
  - name: check
    local_action: stat path=~/.vim/autoload/plug.vim
    register: vimplug
  - name: vim-plug
    shell: |
      mkdir -p ~/.vim/autoload
      cd ~/.vim/autoload
      curl -O https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    when: 
      - vimplug.stat.exists == False

