name: CI to MacOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Check Out Repo
              uses: actions/checkout@v2
            - name: Run
              run: ./test.sh
