name: CI to MacOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Clean
              run: rm -rf '/usr/local/bin/ansible'
            - name: Run
              run: make
